### ISSUE TITLE
java.net.SocketException: sendto failed: EISCONN (Socket is already connected)

### ISSUE THREAD

**Issue by FlyClover** [google/j2objc#636]
I got this exception when making an UDP connection using DatagramChannel:

java.net.SocketException: sendto failed: EISCONN (Socket is already connected)

The codes are roughly like this:
```objective-c
JavaNioChannelsDatagramChannel *datagramChannel = JavaNioChannelsDatagramChannel_open();
[datagramChannel connectWithJavaNetSocketAddress:dstAddr];
[datagramChannel configureBlockingWithBoolean:NO];
[datagramChannel sendWithJavaNioByteBuffer:byteBuffer withJavaNetSocketAddress:dstSocketAddr];
```

Is this issue related to this one https://github.com/robovm/robovm/issues/239?

**Comment by tomball** [comment]
The Android libcore team added several tests to DatagramChannelTest, and
(probably no surprise) they failed after I merged them in. After fixing the
problems found in the Posix datagram socket support, the tests now pass. I
should it reviewed and pushed in the next day or two.

**Comment by kstanger** [comment]
Possibly fixed [in latest source](https://github.com/google/j2objc/commit/f71fe657a29ccaa5df7cb18265e7a0f53a61c2a3). Please re-open if the issue persists.

**Comment by tomball** [comment]
Please reopen if you can attach a test file that demonstrates the failure. Since OS X and iOS share many networking quirks, this can simply be a class with a main() that fails on OS X, or a JUnit test.

**Comment by FlyClover** [comment]
Thanks for the update. But I can still reproduce the using the latest code:

```java
      public void testSend() throws Exception {
        InetSocketAddress addr = new InetSocketAddress("8.8.8.8", 53);
        DatagramChannel datagramChannel = DatagramChannel.open();
        datagramChannel.connect(addr);
        datagramChannel.configureBlocking(false);
        datagramChannel.send(ByteBuffer.wrap(new byte[]{'0'}), addr);
      }

java.net.SocketException: sendto failed: EISCONN (Socket is already connected)
	at 0x0000000103b4ce54 libcore.io.ErrnoException.rethrowAsSocketException() + 38
	at 0x0000000103b4fc28 libcore.io.IoBridge.maybeThrowAfterSendto() + 72
	at 0x0000000103b4fbad libcore.io.IoBridge.sendto() + 203
	at 0x0000000103b2789b java.nio.DatagramChannelImpl.send() + 330
	at 0x0000000103768288 libcore.java.nio.channels.DatagramChannelTest.testConnect() + 232
	at 0x0000000103b8b0b1 java.lang.reflect.Method.invoke:object:() + 231
	at 0x0000000103b8ad53 java.lang.reflect.Method.invoke() + 297
	at 0x0000000103549ef9 junit.framework.TestCase.runTest() + 210
	at 0x0000000103549d8d junit.framework.TestCase.runBare() + 50
	at 0x000000010354b179 junit.framework.TestResult.runProtected() + 37
	at 0x000000010354b110 junit.framework.TestResult.run() + 104
	at 0x000000010354c4ba junit.framework.TestSuite.run() + 250
	at 0x000000010354c4ba junit.framework.TestSuite.run() + 250
	at 0x000000010357298b org.junit.runners.ParentRunner.runChildren() + 320
	at 0x0000000103572dc8 org.junit.runners.ParentRunner.run() + 98
	at 0x000000010356b97f org.junit.runner.JUnitCore.run() + 175
	at 0x000000010356b690 org.junit.runner.JUnitCore.runMain() + 673
	at 0x000000010356b28c org.junit.runner.JUnitCore.runMainAndExit() + 102
	at 0x0000000103b8b0b1 java.lang.reflect.Method.invoke:object:() + 231
	at 0x0000000103b8ad53 java.lang.reflect.Method.invoke() + 297
Caused by: libcore.io.ErrnoException: sendto failed: EISCONN (Socket is already connected)
	at 0x0000000103b53c72 libcore.io.Posix.throwErrnoException() + 9
	at 0x0000000103b56ef7 libcore.io.Posix.sendtoBytes() + 512
	at 0x0000000103b4fb5e libcore.io.IoBridge.sendto() + 124
	at 0x0000000103b2789b java.nio.DatagramChannelImpl.send() + 330
	at 0x0000000103768288 libcore.java.nio.channels.DatagramChannelTest.testConnect() + 232
	at 0x0000000103b8b0b1 java.lang.reflect.Method.invoke:object:() + 231
	at 0x0000000103b8ad53 java.lang.reflect.Method.invoke() + 297
	at 0x0000000103549ef9 junit.framework.TestCase.runTest() + 210
	at 0x0000000103549d8d junit.framework.TestCase.runBare() + 50
	at 0x000000010354b179 junit.framework.TestResult.runProtected() + 37
	at 0x000000010354b110 junit.framework.TestResult.run() + 104
	at 0x000000010354c4ba junit.framework.TestSuite.run() + 250
	at 0x000000010354c4ba junit.framework.TestSuite.run() + 250
	at 0x000000010357298b org.junit.runners.ParentRunner.runChildren() + 320
	at 0x0000000103572dc8 org.junit.runners.ParentRunner.run() + 98
	at 0x000000010356b97f org.junit.runner.JUnitCore.run() + 175
	at 0x000000010356b690 org.junit.runner.JUnitCore.runMain() + 673
	at 0x000000010356b28c org.junit.runner.JUnitCore.runMainAndExit() + 102
	at 0x0000000103b8b0b1 java.lang.reflect.Method.invoke:object:() + 231
	at 0x0000000103b8ad53 java.lang.reflect.Method.invoke() + 297
```

My testing environment is:

Locale: en_US.UTF-8
Darwin xxx.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
Xcode 6.4 Build version 6E35b
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

I also got another test failure:
```java
test_getByName(libcore.java.net.InetAddressTest)
junit.framework.AssertionFailedError: 1.2.3.4.
	at 0x0000000103a093a7 java.lang.AssertionError.<init>() + 35
	at 0x00000001035475fa junit.framework.Assert.fail() + 23
	at 0x00000001039e1cc7 libcore.java.net.InetAddressTest.test_getByName() + 151
	at 0x0000000103b8b0b1 java.lang.reflect.Method.invoke:object:() + 231
	at 0x0000000103b8ad53 java.lang.reflect.Method.invoke() + 297
	at 0x0000000103549ef9 junit.framework.TestCase.runTest() + 210
	at 0x0000000103549d8d junit.framework.TestCase.runBare() + 50
	at 0x000000010354b179 junit.framework.TestResult.runProtected() + 37
	at 0x000000010354b110 junit.framework.TestResult.run() + 104
	at 0x000000010354c4ba junit.framework.TestSuite.run() + 250
	at 0x000000010354c4ba junit.framework.TestSuite.run() + 250
	at 0x000000010357298b org.junit.runners.ParentRunner.runChildren() + 320
	at 0x0000000103572dc8 org.junit.runners.ParentRunner.run() + 98
	at 0x000000010356b97f org.junit.runner.JUnitCore.run() + 175
	at 0x000000010356b690 org.junit.runner.JUnitCore.runMain() + 673
	at 0x000000010356b28c org.junit.runner.JUnitCore.runMainAndExit() + 102
	at 0x0000000103b8b0b1 java.lang.reflect.Method.invoke:object:() + 231
	at 0x0000000103b8ad53 java.lang.reflect.Method.invoke() + 297
```
